version: "3.9"
services:
  power-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: power
      POSTGRES_USER: power
      POSTGRES_PASSWORD: power
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "20012:5432"
    volumes:
      - power-db:/var/lib/postgresql/data
  power-migrator:
    build: .
    depends_on:
      power-db:
        condition: service_healthy
    restart: no
    environment:
      MODE: MIGRATOR
      Database__ConnectionString: "Host=power-db;Port=5432;Username=power;Password=power;Database=power;"
  power:
    build: .
    depends_on:
      power-migrator:
        condition: service_completed_successfully
    restart: no
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "https://+"
      MODE: WEB
      Auth__BaseUrl: "http://auth:80"
      Database__ConnectionString: "Host=power-db;Port=5432;Username=power;Password=power;Database=power;"
    ports:
      - "20010:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx
volumes:
  power-db: